# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: "setup"
  displayName: "Setup"
  jobs:
  - job: "Install"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
  - job: "deps"
    steps:
    - script: yarn install
      displayName: 'Install dependencies'

- stage: "test"
  displayName: "Test project"
  jobs:
  - job: "lint"
    steps:
    - script: yarn lint
      displayName: 'Lint project'

- stage: "build"
  displayName: "Build project"
  jobs:
  - job: "build"
    steps:
    - script: yarn build
      displayName: 'Create a build'

# - stage: "release"
#   displayName: "Release"
#   jobs:
#   - job: "ghrelease"
#     steps:
#     - script: yarn release
#       displayName: 'Cut a release to Github'
